"""
Django settings for portfolio project.

Generated by 'django-admin startproject' using Django 5.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import environ  # Import environ package
import os
import dj_database_url




# Initialise environment variables
env = environ.Env(
    DEBUG=(bool, True),  # Default to True for development
    SECRET_KEY=(str, ''),  # Default to empty string, must be set in .env
    CLOUDINARY_CLOUD_NAME=(str, ''),    # Default to empty string, must be set in .env
    CLOUDINARY_API_KEY=(str, ''),       # Default to empty string, must be set in .env
    CLOUDINARY_API_SECRET=(str, ''),    # Default to empty string, must be set in .env
    DATABASE_URL=(str, ''),  # Default to empty string, must be set in .env
    EMAIL_BACKEND=(str, 'django.core.mail.backends.console.EmailBackend'),  # Default to console backend for development
    EMAIL_HOST=(str, 'localhost'),  # Default to localhost for development
    EMAIL_PORT=(int, 587),
    EMAIL_USE_TLS=(bool, True),
    EMAIL_HOST_USER=(str, ""),
    EMAIL_HOST_PASSWORD=(str, ""),
    CONTACT_EMAIL=(str, ""),
    DEFAULT_FROM_EMAIL=(str, ""),
    SENDGRID_API_KEY=(str, ''),
)
environ.Env.read_env(os.path.join(os.path.dirname(os.path.dirname(__file__)), '.env'))



ENVIRONMENT = env("ENVIRONMENT", default="development")
DEBUG = env.bool("DEBUG", default=(ENVIRONMENT == "development"))


SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

CSRF_COOKIE_SECURE = env.bool("CSRF_COOKIE_SECURE", default=not DEBUG)
SESSION_COOKIE_SECURE = env.bool("SESSION_COOKIE_SECURE", default=not DEBUG)



# Email Config (Development mode using local SMTP server or console backend)
EMAIL_BACKEND = env("EMAIL_BACKEND")
EMAIL_HOST = env.str("EMAIL_HOST")
EMAIL_PORT = env.int("EMAIL_PORT")
EMAIL_USE_TLS = env.bool("EMAIL_USE_TLS", default=False)
EMAIL_HOST_USER = env.str("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = env.str("EMAIL_HOST_PASSWORD")

# Contact email (for receiving messages from a contact form)
CONTACT_EMAIL = env.str("CONTACT_EMAIL", default=EMAIL_HOST_USER)

# contact email (for sending message from a contact form)
DEFAULT_FROM_EMAIL = env("DEFAULT_FROM_EMAIL", default=EMAIL_HOST_USER)

#Email config (production mode using sendgrid)
SENDGRID_API_KEY = env('SENDGRID_API_KEY')


from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')


# SECURITY WARNING: don't run with debug turned on in production!

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['127.0.0.1','localhost','10.175.171.206'])


# Application definition

INSTALLED_APPS = [

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    'portfolioApp',  #portfolio app
    'portfolioAPI',  #portfolio API
    'cloudinary',
    'cloudinary_storage',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',

    # WhiteNoiseMiddleware is used to serve static files in production
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
]

ROOT_URLCONF = 'portfolio.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],  # Directory for custom templates
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',  #
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'portfolio.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Database configuration



# Detect environments
DEBUG = os.getenv("DEBUG", "True") == "True"
ON_RAILWAY = "RAILWAY_ENVIRONMENT" in os.environ
ON_RENDER = "RENDER" in os.environ

if ENVIRONMENT == "development" and not ON_RENDER:
    # Local development (SQLite)
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }

elif ENVIRONMENT == "production" and ON_RAILWAY:
    # Railway Postgres (env vars are injected automatically)
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.getenv("PGDATABASE"),
            "USER": os.getenv("PGUSER"),
            "PASSWORD": os.getenv("PGPASSWORD"),
            "HOST": os.getenv("PGHOST"),
            "PORT": os.getenv("PGPORT"),
        }
    }

elif ENVIRONMENT == "production" and ON_RENDER:
    # Render Postgres (DATABASE_URL is injected automatically)
    DATABASES = {
        "default": dj_database_url.config(
            conn_max_age=600,
            ssl_require=True,
        )
    }

else:
    raise Exception(f"Unknown ENVIRONMENT: {ENVIRONMENT}")

# if USE_RAILWAY_DB:
#     DATABASES = {
#         'default': {
#             'ENGINE': 'django.db.backends.postgresql',
#             'NAME': env('PGDATABASE'),
#             'USER': env('PGUSER'),
#             'PASSWORD': env('PGPASSWORD'),
#             'HOST': env('PGHOST'),
#             'PORT': env('PGPORT'),
#         }
#     }
# else:
#     DATABASES = {
#         'default': {
#             'ENGINE': 'django.db.backends.sqlite3',
#             'NAME': BASE_DIR / "db.sqlite3",
#         }
#     }



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]  # Directory for static files during development
# STATIC_ROOT is used for collecting static files in production
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles') # Directory for collected static files
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

import cloudinary
import cloudinary.uploader
import cloudinary.api
from cloudinary_storage.storage import MediaCloudinaryStorage


DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'


CLOUDINARY_STORAGE = {
    'CLOUD_NAME': env('CLOUDINARY_CLOUD_NAME'),
    'API_KEY': env('CLOUDINARY_API_KEY'),
    'API_SECRET': env('CLOUDINARY_API_SECRET'),
}


# CSRF trusted origins for production
# Add your production domain here, e.g., "https://yourdomain.com"
CSRF_TRUSTED_ORIGINS = env.list("CSRF_TRUSTED_ORIGINS", default=[
    "https://emmibrill.up.railway.app",
])


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

import logging

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'DEBUG',
    },
}
